# æ³¨æ„: æˆè¯¾æ•™å¸ˆæ¿å—å†…å®¹ä¸ºå¾…è¡¥å……çŠ¶æ€ï¼Œè¯·åç»­è´¡çŒ®è€…å®Œå–„ã€‚
course_name = "æœºç”µç³»ç»Ÿæ§åˆ¶åŸºç¡€"
course_code = "MECH3005"
notices = ""

[[lecturers]]
name = "åŒ…æ–Œ"
  [[lecturers.reviews]]
  content = """æˆè¯¾é£æ ¼ï¼šï¼ˆå¾…è¡¥å……ï¼‰
å¬è¯¾å»ºè®®ï¼šï¼ˆå¾…è¡¥å……ï¼‰
â€¦â€¦"""
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "ç‹æ˜•"
  [[lecturers.reviews]]
  content = """æˆè¯¾é£æ ¼ï¼šï¼ˆå¾…è¡¥å……ï¼‰
å¬è¯¾å»ºè®®ï¼šï¼ˆå¾…è¡¥å……ï¼‰
â€¦â€¦"""
  author = { name = "", link = "", date = "" }

textbooks = []
online_resources = []
course = []

[[exam]]
content = "2025 ç§‹è€ƒè¯•ä¸ç®—å¾ˆéš¾ï¼Œæ€»åˆ†å¹³å‡åˆ†ä¼°è®¡æœ‰ 90 åˆ†ã€‚"
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01-01" }

lab = []

[[advice]]
content = """
2025 ç§‹ï¼Œæœ¬è¯¾ç¨‹ç”±ä¸¤ä½è€å¸ˆåˆ†åˆ«è®²æˆåŠå­¦æœŸè¯¾ç¨‹ã€‚

æŒ‰ç™¾åˆ†åˆ¶çš„å¹³æ—¶åˆ†é‡Œæœ‰ 20 åˆ†é€‰åšé¢˜ï¼šå†™ä¸€ç¯‡å°è®ºæ–‡ï¼›è¯¾ä¸Šæ²¡è¯´æ¸…æ¥šæ˜¯å¦æ˜¯é€‰åšé¢å¤–åŠ åˆ†ï¼ˆ100+20=120ï¼‰ã€ä½œä¸šè¯´æ˜é‡Œä¹Ÿæ²¡æœ‰è¯´ï¼Œä½†å°±æœ€åæˆç»©æ¥çœ‹æ˜¯ä¸åš 100-20â€”â€”å¹¶éã€Œé€‰åšé¢˜ã€ğŸ¤£

è¯¾æœ¬ä»‹ç»çš„ Nyquist åˆ¤æ®æ–¹æ³•ä¸æ˜¯å¾ˆå¥½ç”¨ï¼Œå­¦æœ‰ä½™åŠ›~~æˆ–è€…æ ¹æœ¬æ²¡å­¦~~çš„åŒå­¦å¯ä»¥å‚è€ƒè‡ªåŠ¨åŒ–[æ›´å¸¸ç”¨çš„æ–¹æ³•](https://www.bilibili.com/video/BV1ikWneMEhc/)ã€‚"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01-01" }

schedule = []
related_links = []
misc = []